// This file was automatically generated from hero.plist.soy.
// Please don't edit this file by hand.

goog.provide('lime.ASSETS.hero.plist');

goog.require('soy');
goog.require('soydata');


lime.ASSETS.hero.plist.data = function(opt_data, opt_ignored) {
  return '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>frames</key><dict><key>hero-f-0.png</key><dict><key>x</key><real>2</real><key>y</key><real>2</real><key>width</key><real>27</real><key>height</key><real>32</real><key>offsetX</key><real>3</real><key>offsetY</key><real>0</real><key>originalWidth</key><real>32</real><key>originalHeight</key><real>32</real></dict><key>hero-c-1.png</key><dict><key>x</key><real>2</real><key>y</key><real>36</real><key>width</key><real>27</real><key>height</key><real>32</real><key>offsetX</key><real>3</real><key>offsetY</key><real>1</real><key>originalWidth</key><real>32</real><key>originalHeight</key><real>32</real></dict><key>hero-c-2.png</key><dict><key>x</key><real>2</real><key>y</key><real>69</real><key>width</key><real>27</real><key>height</key><real>32</real><key>offsetX</key><real>3</real><key>offsetY</key><real>0</real><key>originalWidth</key><real>32</real><key>originalHeight</key><real>32</real></dict><key>hero-d-1.png</key><dict><key>x</key><real>2</real><key>y</key><real>233</real><key>width</key><real>27</real><key>height</key><real>32</real><key>offsetX</key><real>3</real><key>offsetY</key><real>0</real><key>originalWidth</key><real>32</real><key>originalHeight</key><real>32</real></dict><key>hero-d-2.png</key><dict><key>x</key><real>2</real><key>y</key><real>266</real><key>width</key><real>27</real><key>height</key><real>32</real><key>offsetX</key><real>1</real><key>offsetY</key><real>1</real><key>originalWidth</key><real>32</real><key>originalHeight</key><real>32</real></dict><key>hero-e-1.png</key><dict><key>x</key><real>2</real><key>y</key><real>167</real><key>width</key><real>27</real><key>height</key><real>32</real><key>offsetX</key><real>3</real><key>offsetY</key><real>1</real><key>originalWidth</key><real>32</real><key>originalHeight</key><real>32</real></dict><key>hero-e-2.png</key><dict><key>x</key><real>2</real><key>y</key><real>200</real><key>width</key><real>27</real><key>height</key><real>32</real><key>offsetX</key><real>3</real><key>offsetY</key><real>1</real><key>originalWidth</key><real>32</real><key>originalHeight</key><real>32</real></dict><key>hero-f-1.png</key><dict><key>x</key><real>2</real><key>y</key><real>102</real><key>width</key><real>27</real><key>height</key><real>32</real><key>offsetX</key><real>3</real><key>offsetY</key><real>1</real><key>originalWidth</key><real>32</real><key>originalHeight</key><real>32</real></dict><key>hero-f-2.png</key><dict><key>x</key><real>2</real><key>y</key><real>135</real><key>width</key><real>27</real><key>height</key><real>32</real><key>offsetX</key><real>3</real><key>offsetY</key><real>0</real><key>originalWidth</key><real>32</real><key>originalHeight</key><real>32</real></dict></dict><key>texture</key><dict><key>width</key><integer>1024</integer><key>height</key><integer>512</integer></dict></dict></plist>';
};
